apiVersion: v1
kind: Service

metadata: 
     name: myapp-service
spec: 
  type: NodePort
  ports: 
   - port: 80
     targetPort: 80
     nodePort: 3004

selector: 
    app: myapp           ##labels section  from pod yml files

