kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-rolebinding
  namespace: apache
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apache-role
subjects:
  - kind: ServiceAccount
    name: apache-user
    namespace: apache