kind: Service
apiVersion: v1
metadata:
     name: apache-service
     namespace: apache

spec:
  selector:
      app: apahe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP


  #kubectl port forward service/apache-service 8080:80 -address=0.0.0.0 -n apache